# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'MU' do

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'

  target 'MUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MUUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
